feat(sway): Add the `custom/recorder` module to Waybar

diff --git a/bin/sway-recording b/bin/sway-recording
--- a/bin/sway-recording
+++ b/bin/sway-recording
@@ -1,21 +1,18 @@
 #!/usr/bin/env bash
-# 录屏通知，点击预览
-# @depends: libnotify, dunst, wf-recorder, slurp
-#
-# 1. 只停止当前脚本管理的 wf-recorder 进程
-# 2. 只要存在 wf-recorder 进程则不启动新的进程（无论是当前脚本管理的，还是外部启动的）
+# 开始录屏，可选择全屏/局部，以及含声/无声
+# @depends: libnotify, wf-recorder, slurp
 
 echo "[$$ sway-recording] ---------- $(date +"%Y-%m-%d %T.%6N") ----------" >>/tmp/xreaker.log
 
 ICON=~/.local/share/fa-icons/video.svg
 
 # --- Dependency Check ---
-if ! command -v dunstify >/dev/null; then
-    notify-send -i $ICON -u critical "Recording Error" "dunstify not found. Please install it."
-    exit 1
-fi
 if ! command -v wf-recorder >/dev/null; then
     notify-send -i $ICON -u critical "Recording Error" "wf-recorder not found. Please install it."
+    exit 1
+fi
+if ! command -v slurp >/dev/null; then
+    notify-send -i $ICON -u critical "Recording Error" "slurp not found. Please install it."
     exit 1
 fi
 
@@ -23,108 +20,44 @@ fi
 RECORDINGS_DIR="${XDG_VIDEOS_DIR:-$HOME/Videos}/Recordings"
 mkdir -p "$RECORDINGS_DIR"
 
-FILENAME="Recording_$(date +'%Y-%m-%d-%H%M%S.%N').mkv"
+VIDEO_EXT="mkv"
+FILENAME="Recording_$(date +'%Y-%m-%d-%H%M%S.%N').$VIDEO_EXT"
 FILEPATH="$RECORDINGS_DIR/$FILENAME"
-PID_FILE="/tmp/wf-recorder.pid"          # Stores PID of the active recording process.
-OUTPUT_PATH_FILE="/tmp/wf-recorder.path" # Stores the output file path.
-NOTIFY_ID="9877"                         # Notification ID for replacement/actions.
+RECORDER_LOG="/tmp/wf-recorder.log"
 
 RECORD_ACTION="$1"
 shift
 
-# 只要存在 wf-recorder 进程则不启动新的进程（无论是当前脚本管理的，还是外部启动的）
-if [[ "$RECORD_ACTION" != "stop" ]]; then
-    PID=$(pgrep wf-recorder)
-    if [[ -n "$PID" ]]; then
-        notify-send -i $ICON -u critical "Recording Error" \
-            "Recording (PID: $PID) already in progress. Stop the current recording first."
-        exit 1
-    fi
+# 只要存在 wf-recorder 进程则不启动新的进程（无论是通过当前脚本启动的，还是外部其他方式启动的）
+PID=$(pgrep wf-recorder)
+if [[ -n "$PID" ]]; then
+    notify-send -i $ICON -u critical "Recording Error" \
+        "Recording (PID: $PID) already in progress. Stop the current recording first."
+    exit 1
 fi
 
 # --- Execution Logic ---
 case "$RECORD_ACTION" in
 "output_noaudio")
-    # 1. Execute wf-recorder in background
-    nohup wf-recorder -f "$FILEPATH" >/dev/null 2>&1 &
+    # Execute wf-recorder in background
+    nohup wf-recorder -f "$FILEPATH" 1>$RECORDER_LOG 2>&1 &
 
-    # 2. Store PID and file path
-    echo $! >"$PID_FILE"
-    echo "$FILEPATH" >"$OUTPUT_PATH_FILE"
-
-    echo "[$$ sway-recording] Recording Started, Recording PID $(cat $PID_FILE): $(pgrep --list-full wf-recorder)" >>/tmp/xreaker.log
+    echo "[$$ sway-recording] Recording Started, Process Details: $(pgrep --list-full wf-recorder)." >>/tmp/xreaker.log
     ;;
 "area_noaudio")
-    nohup wf-recorder -g "$(slurp)" -f "$FILEPATH" >/dev/null 2>&1 &
-
-    echo $! >"$PID_FILE"
-    echo "$FILEPATH" >"$OUTPUT_PATH_FILE"
+    nohup wf-recorder -g "$(slurp)" -f "$FILEPATH" 1>$RECORDER_LOG 2>&1 &
     ;;
 "output_audio")
-    nohup wf-recorder -a -f "$FILEPATH" >/dev/null 2>&1 &
-
-    echo $! >"$PID_FILE"
-    echo "$FILEPATH" >"$OUTPUT_PATH_FILE"
+    nohup wf-recorder -a -f "$FILEPATH" 1>$RECORDER_LOG 2>&1 &
     ;;
 "area_audio")
-    nohup wf-recorder -g "$(slurp)" -a -f "$FILEPATH" >/dev/null 2>&1 &
-
-    echo $! >"$PID_FILE"
-    echo "$FILEPATH" >"$OUTPUT_PATH_FILE"
-    ;;
-"stop")
-    [[ -f "$PID_FILE" ]] && PID=$(cat "$PID_FILE") || PID=
-    [[ -f "$OUTPUT_PATH_FILE" ]] && LAST_FILEPATH=$(cat "$OUTPUT_PATH_FILE") || LAST_FILEPATH=
-    [[ -f "$OUTPUT_PATH_FILE" ]] && PATH_UNKNOWN_DETAILS="Output path does not exist." || PATH_UNKNOWN_DETAILS="Output path cache was missing."
-
-    # 确保相应的 wf-recorder 进程存在
-    if [[ -z "$PID" ]] || ! pgrep wf-recorder | grep -q "$PID"; then
-        # 清理内容为空的 PID_FILE
-        rm -f "$PID_FILE"
-        notify-send -i $ICON -u critical "Recording Error" "No active recording found to stop."
-        exit 1
-    fi
-
-    echo "[$$ sway-recording] Recording Process Details: $(pgrep --list-full --pidfile=$PID_FILE)." >>/tmp/xreaker.log
-
-    # 1. Terminate process gracefully
-    kill -SIGINT "$PID"
-    # 2. Wait for process to exit and file writing to complete
-    wait "$PID" 2>/dev/null
-    # 3. Clean up temporary files
-    rm -f "$PID_FILE" "$OUTPUT_PATH_FILE"
-
-    # 确保录屏文件存在
-    if [[ -z "$LAST_FILEPATH" || ! -f "$LAST_FILEPATH" ]]; then
-        notify-send -i $ICON -u normal "Recording Stopped (Path Unknown)" \
-            "Recording (PID: $PID) terminated. $PATH_UNKNOWN_DETAILS"
-        exit 1
-    fi
-
-    # 4. Send blocking stop notification with preview action
-    ACTION_KEY="preview_open"
-    ACTION_LABEL="Preview Recording"
-
-    ACTION_RESULT=$(
-        dunstify --block \
-            --replace="$NOTIFY_ID" \
-            --icon="$ICON" \
-            --action="$ACTION_KEY,$ACTION_LABEL" \
-            "Recording Saved" \
-            "Click to Preview. $LAST_FILEPATH"
-    )
-
-    # --- Handle returned Action ---
-    case "$ACTION_RESULT" in
-    "$ACTION_KEY")
-        # Open preview file
-        /usr/bin/xdg-open "$LAST_FILEPATH"
-        ;;
-    esac
-
+    nohup wf-recorder -g "$(slurp)" -a -f "$FILEPATH" 1>$RECORDER_LOG 2>&1 &
     ;;
 *)
     notify-send -i $ICON -u critical "Recording Error" "Invalid action: $RECORD_ACTION"
     exit 1
     ;;
 esac
+
+# Notify Waybar to update
+pkill -RTMIN+8 waybar
